package com.zerotoler.rpgmenu.domain.model.battle

/**
 * Lightweight frame data for Canvas / HUD — not the full physics graph.
 */
data class BattleRenderSnapshot(
    val tick: Long,
    val phase: BattlePhase,
    val outcome: BattleOutcome,
    val arenaCenterX: Float,
    val arenaCenterY: Float,
    val arenaRadius: Float,
    val showLaunchers: Boolean,
    val launcherPlayerX: Float,
    val launcherPlayerY: Float,
    val launcherEnemyX: Float,
    val launcherEnemyY: Float,
    val playerX: Float,
    val playerY: Float,
    val playerAngle: Float,
    val playerRadius: Float,
    val enemyX: Float,
    val enemyY: Float,
    val enemyAngle: Float,
    val enemyRadius: Float,
    val aimActive: Boolean,
    val aimDirX: Float,
    val aimDirY: Float,
    val powerOscillator01: Float,
    val playerHp: Int,
    val playerHpMax: Int,
    val playerStam: Int,
    val playerStamMax: Int,
    val enemyHp: Int,
    val enemyHpMax: Int,
    val enemyStam: Int,
    val enemyStamMax: Int,
    val timerSec: Int,
    val superMeter: Float,
    val superAbilityActive: Boolean,
    val superAbilityRemainingSec: Float,
    val collisionFlashA: Float,
    val collisionFlashB: Float,
    val screenShakeX: Float,
    val screenShakeY: Float,
    val effects: List<CollisionEffect>,
    val impacts: List<FloatingImpact>,
    val particles: List<BattleParticle>,
    /** Spin-derived RPM for HUD (0..rpmMax). */
    val playerRpm: Int,
    val enemyRpm: Int,
    val playerRpmMax: Int,
    val enemyRpmMax: Int,
    val playerAttacking: Boolean,
    val enemyAttacking: Boolean,
    val playerAttack: Int,
    val playerDefense: Int,
    val playerWeightGrams: Int,
    val enemyAttack: Int,
    val enemyDefense: Int,
    val enemyWeightGrams: Int,
    val playerArchetype: com.zerotoler.rpgmenu.domain.model.CombatType,
    val enemyArchetype: com.zerotoler.rpgmenu.domain.model.CombatType,
) {
    companion object {
        fun empty(): BattleRenderSnapshot = BattleRenderSnapshot(
            tick = 0L,
            phase = BattlePhase.LAUNCH,
            outcome = BattleOutcome.NONE,
            arenaCenterX = 0f,
            arenaCenterY = 0f,
            arenaRadius = (1.1f * 3.5f / 3f * 0.95f),
            showLaunchers = true,
            launcherPlayerX = 0f,
            launcherPlayerY = 0.59f,
            launcherEnemyX = 0f,
            launcherEnemyY = -0.59f,
            playerX = 0f,
            playerY = 0.59f,
            playerAngle = 0f,
            playerRadius = 0.24f,
            enemyX = 0f,
            enemyY = -0.59f,
            enemyAngle = 0f,
            enemyRadius = 0.12f,
            aimActive = false,
            aimDirX = 0f,
            aimDirY = -1f,
            powerOscillator01 = 0f,
            playerHp = 100,
            playerHpMax = 100,
            playerStam = 100,
            playerStamMax = 100,
            enemyHp = 100,
            enemyHpMax = 100,
            enemyStam = 100,
            enemyStamMax = 100,
            timerSec = 90,
            superMeter = 0f,
            superAbilityActive = false,
            superAbilityRemainingSec = 0f,
            collisionFlashA = 0f,
            collisionFlashB = 0f,
            screenShakeX = 0f,
            screenShakeY = 0f,
            effects = emptyList(),
            impacts = emptyList(),
            particles = emptyList(),
            playerRpm = 0,
            enemyRpm = 0,
            playerRpmMax = 100,
            enemyRpmMax = 100,
            playerAttacking = false,
            enemyAttacking = false,
            playerAttack = 0,
            playerDefense = 0,
            playerWeightGrams = 45,
            enemyAttack = 0,
            enemyDefense = 0,
            enemyWeightGrams = 45,
            playerArchetype = com.zerotoler.rpgmenu.domain.model.CombatType.BALANCE,
            enemyArchetype = com.zerotoler.rpgmenu.domain.model.CombatType.BALANCE,
        )
    }
}
